apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: operators:backup-images-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: operators:backup-images-controller
subjects:
- kind: ServiceAccount
  name: backup-images-controller
  namespace: operators